### ISSUE TITLE
Support of stateMutability keywords (pure, view, etc.)

### ISSUE THREAD

**Issue by androlo** [protofire/solhint#1]
Version `1.1.6`, (according to package.json file, but `solhint --version` says `1.1.5`)
 
Using `pure` or other state mutability keywords is currently not supported by the linter, but it is supported by the compiler.

Using `pure` will result in a line like the following:

`line 15:55 extraneous input 'pure' expecting {';', '{', 'returns'}`

Eventually, the line numbers in errors/warnings and other things will be jumbled and will not work properly. Replacing `pure` with `constant` will remove the error.

**Comment by idrabenia** [comment]
Hi @androlo !

Thank you for your feedback!

Fix will be available in next version of Solhint (end of this - next week).

\- Ilya

**Comment by vvlnko** [comment]
@idrabenia, Hi. As far as I can judge, 3.4.1 doesn't allow to find the violation of a style guide when it comes to external view vs external functions not appropriately grouped. Plz fix it

So if we have

external view
external

It won't warn us about it
