### ISSUE TITLE
Use `federicobond/solidity-parser-antlr` instead of using `solidityj/solidity-antlr4` directly

### ISSUE THREAD

**Issue by pablofullana** [protofire/solhint#104]
This will enable us to use the AST in a simpler (higher level) way.
For example, it will let us do `node.stateMutability` instead of parsing/checking the text of each children.

**Comment by yxliang01** [comment]
I am wondering, why not use the official solc to convert to AST? It's free of lacking support of new syntax.

**Comment by fvictorio** [comment]
@yxliang01 Does `solcjs` support this too? If only `solc` allows it, to do this we should download the proper binary when installing solhint. Not saying that it's a bad idea, but we should see if it's worth it.

**Comment by sohkai** [comment]
The potential problem with `solcjs` and `solc` is that they require compiling all the contracts to get the AST, so it takes a lot more resources and time to do (especially annoying if your editor blocks when trying to lint). `solc` in particular, can be annoying to install, and different versions of `solc` support different variants of syntax so you'd also need to specific your contract pragma before being able to lint.
