### ISSUE TITLE
Not allowed to open bracket '{' from new line after constructor/function declaration

### ISSUE THREAD

**Issue by ytumanov** [protofire/solhint#106]
Referring to https://solidity.readthedocs.io/en/develop/style-guide.html#function-declaration when we have long function name, we should open '{' bracket from new line:
![image](https://user-images.githubusercontent.com/6347381/52129102-5c9b7d80-263f-11e9-8200-b025de05de08.png)
When I'm trying to do the same, solhint generates an error 'Open bracket must be on same line. It must be indented by other constructions by space  bracket-align'.

So, i'm not able to make correct declaration with solhint like this:
![image](https://user-images.githubusercontent.com/6347381/52130480-fb75a900-2642-11e9-9c87-4f1bbcd46bb6.png)

And allowed by solhint:
![image](https://user-images.githubusercontent.com/6347381/52130489-02042080-2643-11e9-955e-af1f9fe5b7ab.png)

Thanks

**Comment by fvictorio** [comment]
Closing this since we removed all styling rules. Check the 3.0 release notes for more information.
