### ISSUE TITLE
Add rules for revert reason strings

### ISSUE THREAD

**Issue by nventuro** [protofire/solhint#108]
We'll be working on [revert reasons in OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1709), and it'd be great to have some sort of linter support for this. The two features I can think of are:
a) check that every `require` statement has a reason string
b) check that each reason string is at most N characters long (if it's a literal)

Do you think this is something that makes sense to have in solhint?

**Comment by fvictorio** [comment]
I like this idea a lot. Not sure if it should be a core rule or part of a plugin.

Do you guys think you would like the idea of having a `solhint-plugin-zeppelin`? We could give you a hand with the migration to 2.0 and setting up the plugin if you are interested.

**Comment by sohkai** [comment]
This sounds like it'd be useful as a core rule, where you can use an option to specify the maximum length of each error string (solidity by default allocates 32 bytes worth of space, so the most efficient, outside of doing it in assembly, is to ensure your strings are never more than 32 chars long).

**Comment by nventuro** [comment]
> so the most efficient, outside of doing it in assembly, is to ensure your strings are never more than 32 chars long

This is precisely the intent behind the rule, we've seen contracts become too large due to long revert reasons, and because of that I also think it makes sense as a core rule. We'd be down for having a plugin for more project-specific settings though!
