### ISSUE TITLE
no-simple-event-func-name rule is not case sensitive 

### ISSUE THREAD

**Issue by davesag** [protofire/solhint#12]
I am not sure if this is a bug or a feature but the `no-simple-event-func-name` rule does not see a difference between a function called `claimSatisfied` and an event `ClaimSatisfied`.

Is that rule supposed to be case insensitive?

**Comment by idrabenia** [comment]
Hi @davesag ,

Yes, there is a feature that related to [this](https://github.com/ConsenSys/smart-contract-best-practices/blob/master/docs/recommendations.md#differentiate-functions-and-events) recommendations of ConsenSys Guide for Smart Contracts.

We understand that it may react on some standard contracts like ECR20 and made it the warning severity.

If execution of this rule is not helpful for you - it's possible to disable the rule in configuration file:

"rules": {
    ...
    "no-simple-event-func-name": false,
    ...
}
It's your own choice.

Thank you!
\- Ilya
