### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#122]
The docs right now leave a lot to be desired. I think there are two very important things to do:

1) Add individual pages for all rules, describing what they do and showing code snippets with scenarios where the rule reports and error and where it doesn't.
2) Indicate in the list of rules which ones are enabled when `solhint:recommended` is extended.

**Comment by pablofullana** [comment]
We may need to consider using a tool like the following ones, don't we?
- [readthedocs.io](https://readthedocs.io)
- [gitbook](https://www.gitbook.com/)
- [docusaurus.io](https://docusaurus.io/)

**Comment by fvictorio** [comment]
That would be nice, but I think for a first step just a bunch of markdowns should work. I'm guessing most of those platforms support markdown, so we can do that in another step.

Btw, readthedocs is under `.org`, not `.io`.

**Comment by fvictorio** [comment]
Closed in favor of #137, #138, #139, #140
