### ISSUE TITLE
func-order confused by modifiers and constructors.

### ISSUE THREAD

**Issue by davesag** [protofire/solhint#13]
Running `solhint` over this contract

    pragma solidity ^0.4.18;

    contract TestThing {

        modifier validSender() {
            require(msg.sender != 0x0);
            _;
        }

        function statusIsOkay() external view returns(bool) {
            return true;
        }

        function TestThing() public validSender() {
            // does something
        }
    }

gives error

    11:5  error    Function order is incorrect, external constant function can not go after  function  func-order

**Comment by idrabenia** [comment]
Hi @davesag ,

Thank you for this feedback!

We are fixed this issue and it will be available in next release (at the end of this week). 

\- Ilya
