### ISSUE TITLE
Upgrade grammar to latest version

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#149]
I upgraded the grammar to the latest version but some tests failed. These tests are for the `statement-indent` rule, specifically the tests around `for` statements.

The root of the problem is [this commit](https://github.com/solidityj/solidity-antlr4/commit/fbe865f8ba510cbdb1540fcf9517a42820a4d097): before that, the condition of a `for` was a (potential) expression followed by a semicolon; now the condition is either a expression statement or a semicolon. The result is pretty much the same, but the implications are non trivial for us.

The `statement-indent` rule uses a very contrived logic to check that spaces are alright. Part of this logic is very dependent on this specific aspect of the grammar (grep `forLoopAllCases` and start reading from there, if interested). I don't know how hard is to fix this, but there's a rabbit hole of classes used to check this style stuff.

Upgrading the grammar is *very* important, because we are behind it a lot. But upgrading it without fixing this problem is not an option.

Takeaways:
- Solhint is very coupled with the specifics of the grammar. Using [`solidity-parser-antlr`](https://github.com/federicobond/solidity-parser-antlr) would help a lot, but that refactor won't be trivial **at all**.
- Maintaining style rules is hard. I'm dying for removing all of them and delegating that problem to [`prettier-plugin-solidity`](https://github.com/prettier-solidity/prettier-plugin-solidity), but we should wait for a new major version first (and maybe for the prettier plugin to be at least in beta).

**Comment by pablofullana** [comment]
@fvictorio now that #104 has been merged, shall we close this one?

**Comment by fvictorio** [comment]
Solved in solhint@3.0
