### ISSUE TITLE
Add one-contract-per-file rule

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#154]
According to the [style guide](https://solidity.readthedocs.io/en/v0.5.10/style-guide.html#contract-and-library-names):

> Contract and library names should also match their filenames.
If a contract file includes multiple contracts and/or libraries, then the filename should match the core contract. **This is not recommended however if it can be avoided.**

(Emphasis added)

Checking if the filename matches the contract might be a different rule, or everything could be done in the same rule, I'm not sure.

**Comment by dbale-altoros** [comment]
https://github.com/protofire/solhint/pull/487
