### ISSUE TITLE
Add `reason-string` to recommended ruleset

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#156]
This seems like a good rule to have in the recommended ruleset. But beyond that, I don't think we have a policy for promoting rules to "recommended" (or for demoting them), so I would like to use this issue to have that meta-discussion. Specifically:

1) How is a proposal made? I think just opening an issue should be enough, but it might be a good idea to have this documented somewhere.
2) What criteria should be used for accepting a rule as recommended?
3) How does this affect versioning? Is promoting/demoting rules a breaking change? It would be good to check what eslint does about this.

cc @pablofullana @mariano-aguero

**Comment by pablofullana** [comment]
> 1. How is a proposal made? I think just opening an issue should be enough, but it might be a good idea to have this documented somewhere.

I think we could work on a "recommended rule proposal" template. Making sure that issuer states motivation behind and why it makes sense to have it as a recommended vs an optional rule. Pointing out use cases that reflect its scope (as in: how common it is to have this rule activated) to give a sense of usage.

> 2. What criteria should be used for accepting a rule as recommended?

What about taking into account best practices compliance and, related to previous answer, usage? It's quite important to draw a line between recommended, optional and/or rules to be added via plugins.

> 3. How does this affect versioning? Is promoting/demoting rules a breaking change? It would be good to check what eslint does about this.

I think it is. But I'd like to take a look at how other linters deal with this.

**Comment by fvictorio** [comment]
Oops, I should've done this before releasing 3.0.0. I think _adding_ rules to recommended can be done without a major version though. I'll tag it for a 3.1.0 release.
