### ISSUE TITLE
Add gcc format

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#16]
I tried to integrate solhint with [Ale](https://github.com/w0rp/ale) (a lint engine for vim that takes advantage of vim 8 async features), but I wasn't able to do it because none of the formatters is supported by Ale, at least right now. There is support for the `unix` format, but it can't tell warnings from errors.

Adding a `gcc` formatter to solhint seems to me like the easiest way to do it.

**Comment by sohkai** [comment]
I took a stab at implementing a checker for ale ([commit on my fork](https://github.com/sohkai/ale/commit/b896557566e780f5666280be8f0fb2b303606c4d)) but didn't get a chance to test it out yet.

I think I just took the ESLint checker's regexes and simplified it. Does something like [this](https://github.com/sohkai/ale/commit/b896557566e780f5666280be8f0fb2b303606c4d#diff-5a80e0d622a925200734d7facfc50b22R26) not work for differentiating warnings from errors?

**Comment by fvictorio** [comment]
Hi @sohkai.

I ended up using the `compact` format (it's not documented here in solhint, but it's available since solhint just delegates the formatting to eslint formatters). You can see mi PR here: w0rp/ale#1192.

**Comment by sohkai** [comment]
Yeah, I think I had to do the same for syntastic and neomake :). Actually, maybe it'd be cool if it was made more explicit?

**Comment by mgarciap** [comment]
Hi @fvictorio @sohkai did you agree on how the format be handled? Does it make sense to have this open or should we close it and go for #19 ?

**Comment by fvictorio** [comment]
Sure.
