### ISSUE TITLE
A function named 'leave' breaks solhint

### ISSUE THREAD

**Issue by AleG94** [protofire/solhint#201]
Having a function named `leave` like this one will break solhint validation.

```
function leave() public {
     // something
}
```

Executing solhint returns:

`Error: ParserError: no viable alternative at input 'functionleave'`

Version: 3.0.0-rc.5

**Comment by fvictorio** [comment]
Hi @AleG94, thanks for reporting this. It seems like a problem with the parser we are using, I'll open a related issue.

**Comment by fvictorio** [comment]
Hey @AleG94, sorry this took so long. Could you please check the latest `next` version and see if this still happens?

**Comment by AleG94** [comment]
No worries, I can confirm it works on `3.0.0-rc.7`. Thank you!
