### ISSUE TITLE
Release candidate tagged as 'latest'

### ISSUE THREAD

**Issue by nventuro** [protofire/solhint#202]
v3.0.0-rc.5 is currently tagged as 'latest' on npm, with 'next' being v3.0.0-rc.3:

![image](https://user-images.githubusercontent.com/2530770/76436184-aacc9580-6396-11ea-99d5-58e41ab3566e.png)

'latest' has an important meaning in the npm registry: it is the version that will be installed by default when no tag or version is specified. In other words, people running `npm install solhint` will have the release candidate installed, not v2.3.0.

The 'latest' tag should be removed from v3.0.0-rc.5 and applied to v2.3. The `npm dist-tag` subcommand can be used to achieve this.

**Comment by fvictorio** [comment]
Yes, I forgot a `--tag next` during a publish. It should be fixed now, thanks!
