### ISSUE TITLE
Check that all revert reasons are different

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#205]
If a contract has more than one require/revert with the same reason, and one of them is triggered in a transaction, you don't have a way to tell apart between them.

Ideally this rule should be cross-file, but we don't have support for that (yet?)

**Comment by dbale-altoros** [comment]
I'm not sure that now this rule can be a good addition considering that custom error is being used in favor of requires 
And, for now, the cross file check seems kind of a quite long term addition
