### ISSUE TITLE
Plugin error on version 3.0.0-rc.6

### ISSUE THREAD

**Issue by Jaime-Iglesias** [protofire/solhint#207]
I'm doing some testing with plugins around this version and when I try to use a custom plugin I get the message `plugins.map is not a function`

I don't get the error if I just put `"plugins": []"`

my `.solhint.json` looks like so:

![test](https://user-images.githubusercontent.com/22358726/78378849-7630b000-75c9-11ea-8c81-0cf4b006c37d.png)

Without plugins it works just fine.

**Comment by fvictorio** [comment]
You get the error if you do `"plugins": ["cmf-rules"]` but not if you do `"plugins": []`?

If that's the case, that's very weird. Thanks for reporting it!

**Comment by Jaime-Iglesias** [comment]
> You get the error if you do `"plugins": ["cmf-rules"]` but not if you do `"plugins": []`?
> 
> If that's the case, that's very weird. Thanks for reporting it!

@fvictorio I found that very weird too, but I've tried several times and that's indeed the case hahaha.

btw, totatlly unrelated, is `solidity-parser-antlr` the only thing holding back the full `0.6.x` syntax support for the `RC` version ?

**Comment by Jaime-Iglesias** [comment]
@fvictorio Did some extra testing and it works just fine, it was totally my fault (I was missing a `export`)

I'm closing the issue as it's solved - apologize again.

**Comment by fvictorio** [comment]
Hmm, sound like we should show a better when whatever is exported in the plugin is wrong. I will reopen this issue to track that improvement.

**Comment by fvictorio** [comment]
> I will add, that writting custom rules is now easy as pie compared to the previous version - great job!

Thanks btw! That was the main goal of a huge refactor we did :smile:

**Comment by Jaime-Iglesias** [comment]
> Hmm, sounds like we should show a better error when whatever is exported by the plugin is wrong. I will reopen this issue to track that improvement.

if it helps, what I was missing was the `module.exports` with all the clases in my custom rules.

**Comment by fvictorio** [comment]
Fixed in `v3.0.0-rc.8`

![image](https://user-images.githubusercontent.com/417134/79642323-38a85700-8173-11ea-880d-b191a835f3a5.png)
