### ISSUE TITLE
Nested solhints for mixed solidity linting

### ISSUE THREAD

**Issue by justinjmoses** [protofire/solhint#211]
We have a situation where one folder of contracts is using an older compiler version. I was hoping that nested `.solhint.json` files would work like eslint - that is, any rules in a folder overrides rules in a parent folder but that doesn't seem to be the case.

For instance on this repo: https://github.com/justinjmoses/solhint-nesting-example 

You'd expect running `npx solhint "contracts/**/*.sol` would succeed as `contracts/legacy/.solhint.json` overrides the root `.solhint.json` but that doesn't seem to be the case. 

Is there another way to achieve what I'm after, or is it a pending feature?

**Comment by fvictorio** [comment]
Hi @justinjmoses, thanks for reporting this.

In this specific scenario you can do something like this:

```
npx solhint -c .solhint.json contracts/A.sol 
npx solhint -c contracts/legacy/.solhint.json contracts/legacy/ALegacy.sol
```

But of course in a more realistic scenario this won't work. One workaround I can think is having a `.solhint-ignore-legacy` with `contracts/legacy` inside and then doing:

```
npx solhint -c .solhint.json --ignore-path .solhint-ignore-legacy 'contracts/**/*.sol.sol'
npx solhint -c contracts/legacy/.solhint.json 'contracts/legacy/**/*.sol'
```

That being said, supporting nested config files would be great, but I don't think we'll be able to work on that soon.

**Comment by justinjmoses** [comment]
Understood and I appreciate the quick follow up @fvictorio

**Comment by fvictorio** [comment]
Awesome. Let me know if that approach works for you. Please reopen if you think it's not enough.
