### ISSUE TITLE
Change project description on GitHub

### ISSUE THREAD

**Issue by tsujp** [protofire/solhint#212]
The current description is verbose and favours crediting protofire before describing what is actually does for sentence 2.

```
Solhint is an open source project created by https://protofire.io. Its goal is to provide a linting utility for Solidity code.
```

A better, concise description would be

```
Open source linter for Solidity.
```

It is already apparent that this is a project from protofire as there is `protofire / solhint` in the top-left on GitHub not to mention the repo's location is `https://github.com/protofire/solhint`.

**Comment by dbale-altoros** [comment]
Done
