### ISSUE TITLE
func-order error always shown for external functions

### ISSUE THREAD

**Issue by szerintedmi** [protofire/solhint#22]
I always get `Function order is incorrect, external constant function can not go after function. (func-order)` solhint error for external functions.

(using solhint in Atom)

```sol
pragma solidity 0.4.18;


contract SolhinTest {
    function get() external view returns (uint ct) { // solhint error: func-order on this line
        return 1;
    }
}

```

**Comment by idrabenia** [comment]
Hi @szerintedmi ,

Thank you for the feedback!

You may download new version of [atom-solidity-linter](https://atom.io/packages/atom-solidity-linter).
It must not contain this issue.

Thanks!
\- Ilya

**Comment by szerintedmi** [comment]
works now, thank you for the quick fix! :)
