### ISSUE TITLE
Errors thrown in rules are being ignored

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#223]
This is very important for sanity checks and for detecting problems in general. For some reason, thrown errors in rules are being ignored. We should, of course, log them and exit with a non-zero value.

**Comment by vadiminc** [comment]
any updates? when it will be fixed?

**Comment by fvictorio** [comment]
> any updates? when it will be fixed?

What do you mean? This is an internal problem and users shouldn't care too much about it.

**Comment by dbale-altoros** [comment]
do you have any example of a thrown error being ignored ?

**Comment by fvictorio** [comment]
No, you just need to add a `throw new Error()` in some rule's implementation.

**Comment by dbale-altoros** [comment]
I will re open if I find this kind of error...
I did not find any alike.
