### ISSUE TITLE
Rules break with new syntax for sending ether or gas to external contracts

### ISSUE THREAD

**Issue by opz** [protofire/solhint#227]
`f.value(x).gas(g)()` is deprecated in favor of `f{value: x, gas: g}()` as of 0.6.2 ([docs](https://solidity.readthedocs.io/en/v0.6.7/control-structures.html#external-function-calls)).

- **no-unused-vars** does not detect variables x or g.
- **indent** detects incorrect indentation.
- **bracket-align** warns open bracket must be on the same line.

**Comment by fvictorio** [comment]
Hi @opz. That new syntax should work with solhint@3. We might add support for it in version 2 if there's enough demand, but it will take some time. Here's the release in case you're interested in upgrading: https://github.com/protofire/solhint/releases/tag/v3.0.0

**Comment by opz** [comment]
Thanks @fvictorio, looks like buidler-solhint was using v2.0.0. I'll close the issue.
