### ISSUE TITLE
Add rule for payable fallbacks

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#228]
The [docs](https://solidity.readthedocs.io/en/v0.6.0/contracts.html#receive-ether-function) say:

> using payable fallback functions for receiving Ether is not recommended, since it would not fail on interface confusions

So adding a rule for that would make sense.

**Comment by dbale-altoros** [comment]
It is not the same as you suggested 
We found this approach more acceptable
[improved](https://github.com/protofire/solhint/pull/561)
