### ISSUE TITLE
space-after-comma error when ommiting vars in tuple assignment

### ISSUE THREAD

**Issue by szerintedmi** [protofire/solhint#23]
I receive space-after-comma error for:
```
var (x, , ,y,) = myContract.get(); // space-after-comma error
var (x,  ,  ,y , ) = myContract.get(); // space-after-comma error
```

**Comment by idrabenia** [comment]
Hi @szerintedmi ,

Thank you for the feedback!

Fix for this issue will be available in the next release of solhint (during 1-2 weeks)

Best Regards,
\- Ilya
