### ISSUE TITLE
`compiler-version` does not work with default value

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#230]
Reproduction:

```solidity
pragma solidity ^0.4.0;

contract Foo {}
```

```
{
  "rules": { "compiler-version": "error" }
}
```

## Expected

Use default value for the compiler version (`^0.5.8`)

## Result

```Foo.sol
  1:1  error  Compiler version ^0.4.0 does not satisfy the r semver requirement  compiler-version
```

Adding square bracket to the rule (`"compiler-version": ["error"]`) works as expected.

**Comment by joaoh9** [comment]
just add the compiler version to .solhint.json

```
  "rules": {
    "compiler-version": ["error", "^0.7.3"]
  }
```

**Comment by fvictorio** [comment]
@joaoh9 this is about solhint not using the default value for that parameter, it's not a question.

**Comment by GAUTAMRAJU15** [comment]
> just add the compiler version to .solhint.json
> 
> ```
>   "rules": {
>     "compiler-version": ["error", "^0.7.3"]
>   }
> ```
> 
> also, are you sure you want to run 0.4.0 solidity version in 2020/2021?

doesn't work. I am using >=0.7.0 <0.9.0;

**Comment by fvictorio** [comment]
@GAUTAMRAJU15 what do you mean by "doesn't work"? Anyway, this issue is for a different scenario, if something doesn't work for you and you have reproduction steps, please open a different issue.

**Comment by MasterTraderMel** [comment]
Noob question, how can I add compiler version to .solhint.json. Where can I find the .solhint.json?

**Comment by aspiers** [comment]
I am using the solhint plugin to remix, and I see this same error:

    contracts/test.sol:1:1: Error: Compiler version ^0.8.4 does not satisfy the r semver requirement

when `test.sol` starts with this:

    pragma solidity ^0.8.4;

Is this the same bug (i.e. with the default value in solhint), or a bug with https://github.com/protofire/remix-solhint-plugin, or am I doing something wrong?

**Comment by jwhitty1** [comment]
I also have this bug that aspiers has but im not using any plugins... following FCC solidity full course and the video just chugs along but i copy line for line, button click for button click, and i get this error...

**Comment by hendrikvanderplas** [comment]
I have the same error on some imported (chainlink) interfaces. Solhint [documentation](https://protofire.github.io/solhint/docs/rules/security/compiler-version.html) requires version ^0.5.8. 

Seems to me that as long as you use a pragma version higher than the minimum required it should be no issue. But yet when imported interfaces of the correct pragma version are used the error is thrown. If I am able to find out where this issue originates I will update this answer.

**Comment by kFuQ** [comment]
add this right above your pragma line


// solhint-disable-next-line
pragma solidity ^0.8.0;

**Comment by jdmedeiros** [comment]
This is a bug; I wish I knew enough to fix it. This:
`pragma solidity ^0.8.7;`
yields
`simple_storage.sol:2:1: Error: Compiler version ^0.8.7 does not satisfy the r semver requirement`
but this:
`pragma solidity ^0.8.7.0;`
will not throw an error.

**Comment by markobonna** [comment]
> This is a bug; I wish I knew enough to fix it. This: `pragma solidity ^0.8.7;` yields `simple_storage.sol:2:1: Error: Compiler version ^0.8.7 does not satisfy the r semver requirement` but this: `pragma solidity ^0.8.7.0;` will not throw an error.

this worked for me, adding a .0 to the end of whatever solidity version i am using

**Comment by DarbyMcB** [comment]
> > This is a bug; I wish I knew enough to fix it. This: `pragma solidity ^0.8.7;` yields `simple_storage.sol:2:1: Error: Compiler version ^0.8.7 does not satisfy the r semver requirement` but this: `pragma solidity ^0.8.7.0;` will not throw an error.
> 
> this worked for me, adding a .0 to the end of whatever solidity version i am using

This makes me think that it just ignores leading zeroes for major version number (skipping to 8) and then complains that there's not a third number for patch. Luckily it seems harmless.

**Comment by dbale-altoros** [comment]
fixed in
https://github.com/protofire/solhint/pull/483

Sorry for the late response
We are trying to catch up with issues and updates
Thanks for posting!!
