### ISSUE TITLE
TypeError: cannot ready property 'errorCount' of undefined

### ISSUE THREAD

**Issue by PaulRBerg** [protofire/solhint#239]
## Description
Happens on Windows 10 version 1909 when running `solhint` as a local dependency installed with yarn 1.22.4.

Happens in both PowerShell and Git's Mingw64.

![Annotation 2020-07-26 163533](https://user-images.githubusercontent.com/8782666/88480324-1d14cf80-cf5e-11ea-889a-fa013eb6e43a.jpg)

## Steps to Reproduce

1. Clone https://github.com/paulrberg/solidity-template
2. Install dependencies with yarn
3. Run `yarn lint:sol`

**Comment by fvictorio** [comment]
Hey @PaulRBerg, this is really weird :/ I can't reproduce it neither in Linux nor in a Windows 10 virtual machine.

**Comment by PaulRBerg** [comment]
Hmm .. weird. Now it works on my end too.

I just started using Windows 10 after a long time on Mac .. maybe I got my setup wrong when I opened this issue.

**Comment by fvictorio** [comment]
> I just started using Windows 10 after a long time on Mac

I'm sorry to hear that :slightly_frowning_face:

**Comment by PaulRBerg** [comment]
Haha, it's temporary! My Mac had a hardware fault and I left it at the repair store.

**Comment by wighawag** [comment]
I am getting the same error in my CI :

```
solhint -w 0 src/**/*.sol

/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/solhint.js:97
    if (program.maxWarnings && !reports[0].errorCount && warningsNumberExceeded) {
                                           ^

TypeError: Cannot read property 'errorCount' of undefined
    at Command.execMainAction (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/solhint.js:97:44)
    at Command.listener (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/node_modules/commander/index.js:656:12)
    at Command.parse (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/node_modules/commander/index.js:474:21)
    at init (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/solhint.js:42:11)
    at Object.<anonymous> (/home/runner/work/sandbox-private-contracts/sandbox-private-contracts/node_modules/solhint/solhint.js:209:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wighawag** [comment]
Any luck in finding what could cause this ?
I tried adding check for removing the errorCount of undefined but the issue is deeper, because if I do that while the error do not appear anymore, the lint pass while it should not (1 warning with --max-warnings 0)

**Comment by wighawag** [comment]
Oh actually I found the issue, I needed to escape the glob pattern. nevermind then :)

**Comment by aspiers** [comment]
I see this too and escaping the glob pattern doesn't help (actually I'm not sure why it would?)

I think this needs to be reopened.

**Comment by aspiers** [comment]
I found the problem - my `.solhintignore` file was causing all the input files to be ignored, in which case, `reports` ends up being `[]`, therefore `reports[0]` is obviously `undefined`.  So the bug is in the line 97 above incorrectly assuming that `reports` will always be non-empty.  Yet another case of [the billion dollar mistake](https://hinchman-amanda.medium.com/null-pointer-references-the-billion-dollar-mistake-1e616534d485) ...

**Comment by sebastiantf** [comment]
> I found the problem - my `.solhintignore` file was causing all the input files to be ignored, in which case, `reports` ends up being `[]`, therefore `reports[0]` is obviously `undefined`. So the bug is in the line 97 above incorrectly assuming that `reports` will always be non-empty. Yet another case of [the billion dollar mistake](https://hinchman-amanda.medium.com/null-pointer-references-the-billion-dollar-mistake-1e616534d485) ...

I'm facing the same issue. Any way to reopen this issue, or should I open a new one?
