### ISSUE TITLE
Proper error output for parse errors

### ISSUE THREAD

**Issue by geigerzaehler** [protofire/solhint#245]
Currently parse errors cause an exception which results in `solhint` aborting and printing the Javascript stack trace. This makes it difficult to extract parse errors from the output for IDE integration for example. Ideally parse errors would show like any other hint error.

I’m happy to provide a patch.

**Comment by fvictorio** [comment]
Makes sense! This is also what eslint does. Feel free to open a PR, and let me know if you have questions or need some pointers.
