### ISSUE TITLE
Linter counts immutable vars as state vars

### ISSUE THREAD

**Issue by gitpusha** [protofire/solhint#258]
Hi, 

For the `max-states-count` rule, the linter counts `immutable` vars as state variable declarations, which shouldnt be the case, right? 

See: 
![image](https://user-images.githubusercontent.com/36712489/96455015-ec6eca00-121c-11eb-982f-4be9fda267c1.png)

**Comment by fvictorio** [comment]
![image](https://user-images.githubusercontent.com/417134/96456683-3643ba00-11f5-11eb-907e-0cc1a45fbc9c.png)

**Comment by fvictorio** [comment]
Pretty sure it's a bug tho

**Comment by gitpusha** [comment]
Yeah, I guess the rule was invented with saving on sloads/sstores in mind, right?

**Comment by fvictorio** [comment]
That rule is before my time, but maybe? I always interpreted it as "don't make contracts that are too complex"
