### ISSUE TITLE
Error on import not found, when import is in fact found

### ISSUE THREAD

**Issue by deluca-mike** [protofire/solhint#259]
Similar to #32 , when I import a contract that I have installed (va some npm package, my own) I get an error that it cannot be found, when it in fact can, and compiles without issue.

`npm install merkle-trees` or `yarn add merkle-trees`

```
import "merkle-trees/eth/contracts/libraries/calldata/bytes/standard/merkle-library.sol";
```

`Source "merkle-trees/eth/contracts/libraries/calldata/bytes/standard/merkle-library.sol" not found: File import callback not supported`

**Comment by fvictorio** [comment]
But solhint doesn't have (yet) a rule for missing imports. That seems like an error from the compiler or from some framework.

**Comment by deluca-mike** [comment]
@fvictorio You're right, its `vscode-solidity`'s fault. Closing.
