### ISSUE TITLE
Feature Request: no-unused-imports

### ISSUE THREAD

**Issue by gitpusha** [protofire/solhint#260]
A rule for warning/error about any unused imports.

**Comment by paulrberg** [comment]
This would be super useful, especially when importing specific symbols like this:

```solidity
import {symbol1 as alias, symbol2} from "filename";
```

**Comment by dbale-altoros** [comment]
This it is also added in this pr
https://github.com/protofire/solhint/pull/417

Will be available in next version

**Comment by PaulRBerg** [comment]
@dbale-altoros is `no-unused-imports` now available in v3.6.2?

**Comment by dbale-altoros** [comment]
@PaulRBerg it is
