### ISSUE TITLE
Command line flag for searching specific rules

### ISSUE THREAD

**Issue by maurelian** [protofire/solhint#27]
I would like to be able to lint a set of contracts for a specific rule. 

That might look like:

`solhint --rule no-empty-blocks contracts/**/*.sol`

Does this fit with the vision?

**Comment by mgarciap** [comment]
@idrabenia @fvictorio ?

**Comment by fvictorio** [comment]
Wow, I totally missed this issue.

This shouldn't be hard to do, although I'm not sure how many people would use it. @maurelian are you still interested on this? Sorry for the huge delay.

**Comment by dbale-altoros** [comment]
Not planned as we think it is something very valuable (I mean, doesn't seem something to be used a lot)
On top of that, it is not a very straightforward option but you can make a `.solhint.json` with just that rule to achieve that

Sorry for the late response.
There is a new release available and we will be updating solhint on regular basis with a dedicated team to it
Thanks for posting
