### ISSUE TITLE
Remove immutable state vars from var-name-mixedcase 

### ISSUE THREAD

**Issue by gitpusha** [protofire/solhint#270]
Like `constant` state vars I also like to `snake-case` my `immutable` state vars because it makes it easier to spot in my code where I am relying on immutable values. 

![image](https://user-images.githubusercontent.com/36712489/98229348-13860500-1f5a-11eb-8744-9c821b6fe128.png)

However, currently this clashes with two rules I also use: 

1. `var-name-mixedcase` forces me to also make `immutable` mixed-case 

2. `const-name-snakecase` does not force me to make `immutable` snake-case

I would like to propose one of the following alterantives as feature requests: 

Alternative 1: New rule: `immutable-name-snakecase` that when turned on overrides the `var-name-mixedcase` rules. 

Alternative 2: `strict` option for `var-name-mixedcase` which when `false` does not include `immutable` vars && `strict` option for `const-name-snakecase` that when `true` also forces `immutable` vars to be `snakecase`

**Comment by frangio** [comment]
I ran into this as well.

I would actually suggest that `immutable` variables should be treated exactly like `constant` variables as far as these rules are concerned (`var-name-mixedcase` and `const-name-snakecase`).

**Comment by gitpusha** [comment]
I guess some people still like to make `immutable` vars `mixed-case` because they do not have to be `initialized` like `constant` vars and that sort of sets them apart. 

So I think having the extra `immutable-name-snakecase` rule would be benificial for both groups.

**Comment by hellwolf** [comment]
yes please!

**Comment by dbale-altoros** [comment]
see this PR
https://github.com/protofire/solhint/pull/458
will add new rule to treat immutable as constants or mixed case as needed
