### ISSUE TITLE
bug: solhint ordering 

### ISSUE THREAD

**Issue by gitpusha** [protofire/solhint#274]
`"solhint": "3.3.2",` 

`"ordering": "error",`

doesnt seem to work e.g [here](https://github.com/gelatodigital/gelato-instadapp/blob/7bbbe0d15831ef6653dfcf264ae94d56dc0823c0/contracts/contracts/connectors/ConnectGelatoDataFullMakerToMaker.sol#L81).

**Comment by gitpusha** [comment]
In general `solhint` `ordering` rule doesnt seem to work for functions that use a `virtual` modifier.

**Comment by gitpusha** [comment]
In general `solhint` 's ordering rule seems to diverge a fair bit from the [solidity style guide](https://docs.soliditylang.org/en/latest/style-guide.html#order-of-functions) ones.

I believe solhint ordering tries to enforce: 

1. external 
2. external view/pure 
3. public 
4. public view/pure 
5. internal
6. private

when I think the rule set should be (according to solidity docs): 

1. external 
2. external view 
3. external pure
4. public 
5. public view 
6. public pure 
7. internal 
8. internal view 
9. internal pure
10. private
11. private view 
12. private pure 

right? 

I guess too much of a pain to implement the granularity but I guess you could simplify and still be much more compliant with the official style guide like so: 

1. external 
2. external view/pure
3. public 
4. public view/pure 
5. internal 
6. internal view/pure 
7. private 
8. private view/pure

**Comment by fernandomg** [comment]
Hey @gitpusha, you're right we're missing the view/pure modifiers for internal and private functions.

I'll give it a look and come back to you with an approach.

Thank you!

**Comment by gitpusha** [comment]
Hi @fernandomg thanks for your time! 

> doesnt seem to work e.g here.
Also the initial issue what seems to be an actual bug in the existing rule set because `solhint` doesnt complain about `public view` coming before `external payable` [here](https://github.com/gelatodigital/gelato-instadapp/blob/7bbbe0d15831ef6653dfcf264ae94d56dc0823c0/contracts/contracts/connectors/ConnectGelatoDataFullMakerToMaker.sol#L81) for example.

You can clone the repo and run `yarn lint:sol` to see that it doesnt complain. I noticed this deficiency in the `ordering` rule in many other places too.

**Comment by fernandomg** [comment]
@gitpusha, So, in your particular case, the ordering rule didn't recognize the `using for` directive.

So when it reached that contract part, it should have thrown an error message like _"Unrecognized contract part, please report this issue"_. That is not happening, I still need to fix it.

On the other hand, I managed to adapt the rule to support the most granular approach:

> 1. external
> 2. external view
> 3. external pure
> 4. public
> 5. public view
> 6. public pure
> 7. internal
> 8. internal view
> 9. internal pure
> 10. private
> 11. private view
> 12. private pure

I'll let you know when I have something deliverable.

Thank you!

**Comment by fernandomg** [comment]
@gitpusha, please feel free to review and validate #275

**Comment by gitpusha** [comment]
@fernandomg I did a review and it looks correct to me :) When do you think you will merge?

**Comment by gitpusha** [comment]
thx for the merge @fernandomg 👍
