### ISSUE TITLE
solidity >= 0.7.4 - free functions visibility 

### ISSUE THREAD

**Issue by gitpusha** [protofire/solhint#276]
Solidity greater than 0.7.4 allows you to have file-level function definitions. 

Solidity forces you not to give them a `visibility modifier` because they are always `pure` by default. 

`solhint` still complains about visibility modifier specification for such solidity function definition files.

**Comment by dbale-altoros** [comment]
this is the same as this one right ?
[#310](https://github.com/protofire/solhint/issues/310)

**Comment by dbale-altoros** [comment]
solved here
https://github.com/protofire/solhint/pull/396
