### ISSUE TITLE
Unchecked support

### ISSUE THREAD

**Issue by juanfranblanco** [protofire/solhint#280]
Hi hope you are well,

In the latest the parser fails with unchecked. Maybe is fixed already :)

![image](https://user-images.githubusercontent.com/562371/108621927-9cec1500-742d-11eb-9d42-2f0a9e9e2c1f.png)

Edit: I have seen that the parser has been updated.

**Comment by mudgen** [comment]
@fernandomg, is this fixed yet?  Need it.  Thanks.   This is for Solidity 0.8.*

**Comment by mudgen** [comment]
@idrabenia or @fvictorio can you please fix this?

**Comment by gitpusha** [comment]
@mudgen 

> Is this project being maintained anymore?

I don't think it currently is.

**Comment by fvictorio** [comment]
I just published `solhint@3.3.3` that ugprades the parser to the latest version. Please let me know if it fixes this for you.

**Comment by fvictorio** [comment]
Btw @mudgen please don't tag people like that, it's annoying. Ilya hasn't worked on this project for a while, for example.

**Comment by mudgen** [comment]
> I just published `solhint@3.3.3` that ugprades the parser to the latest version. Please let me know if it fixes this for you.

Great, thank you!

> Btw @mudgen please don't tag people like that, it's annoying. Ilya hasn't worked on this project for a while, for example.

oh, sorry about this.  I won't.   What should I do in a case like this?

**Comment by fvictorio** [comment]
> oh, sorry about this. I won't. What should I do in a case like this?

Comment without tagging unless you know for sure that the person you are tagging doesn't mind.

**Comment by mudgen** [comment]
> > oh, sorry about this. I won't. What should I do in a case like this?
> 
> Comment without tagging unless you know for sure that the person you are tagging doesn't mind.

Understood, thank you.

**Comment by mudgen** [comment]
Hey, the parser has been fixed: https://github.com/protofire/solhint/issues/280#issuecomment-790849802

**Comment by mudgen** [comment]
Hey, the parser has been fixed: https://github.com/protofire/solhint/issues/280#issuecomment-790849802

**Comment by fvictorio** [comment]
Thank you. Please re-open if something related to this is not working.
