### ISSUE TITLE
Rule request: disallow underbar prefix for function parameter names

### ISSUE THREAD

**Issue by fulldecent** [protofire/solhint#300]
Underbar prefix in variables names has a reserved meaning: private variables.

This is important because switching private to non-private is a big deal and that will require you to touch every part of code that references.

Therefore using underbar prefix in other contexts dilutes this important meaning and I recommend we disallow it.

**Comment by dbale-altoros** [comment]
This is not planned as in the Solidity Style Guide is suggested
https://docs.soliditylang.org/en/latest/style-guide.html#underscore-prefix-for-non-external-functions-and-variables

As a matter of fact, I think it will be a good idea to enforce the use of an underscore for private and internal functions as documentation suggests
