### ISSUE TITLE
can solhint be used in a pre-commit hook with lint-staged and husky

### ISSUE THREAD

**Issue by aster2709** [protofire/solhint#306]
solhint file_name lints the file, but when I try to add it in lint-staged, it doesn't do anything for some reason, shouldn't it throw all the linting warnings?

**Comment by aster2709** [comment]
example: 
![image](https://user-images.githubusercontent.com/39130640/129356713-7a56bd35-f7ce-4942-b90e-85797ab33808.png)

**Comment by dbale-altoros** [comment]
@aster2709 did you solve this ?
Can you provide the script where you execute solhint ? and the .solhint.json ?

Sorry for the late response. 
There is a new version release and we will be updating solhint on regular basis
Thanks for posting!
