### ISSUE TITLE
Upgrade antlr to 4.9

### ISSUE THREAD

**Issue by rootulp** [protofire/solhint#309]
Currently, consumers of solhint will observe warnings like the following when running `yarn install`:
```
(node:7265) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(node:7265) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```
This is caused by https://github.com/antlr/antlr4/issues/2834 and resolved by https://github.com/antlr/antlr4/pull/2931 which was released in [antlr 4.9](https://github.com/antlr/antlr4/releases/tag/4.9). Therefore it would be awesome if solhint upgraded to this release.

**Comment by dbale-altoros** [comment]
Updated to 4.11 in master branch. Will be included in next release
