### ISSUE TITLE
Solhint tags free functions for visibility?

### ISSUE THREAD

**Issue by grapevinegizmos** [protofire/solhint#310]
Can't get rid of linter message on free function:

If i put
`function roleValue(Role role) pure returns(bytes32) {...}`

before the contract body, I get an linter warning `Explicity mark visibility in function [func-visiblity] [7,1]` which of course is unavoidable since you can't mark visibility on a free function.

**Comment by dbale-altoros** [comment]
Same Issue ?
[#339](https://github.com/protofire/solhint/issues/339)
