### ISSUE TITLE
Json format for the output

### ISSUE THREAD

**Issue by omarandres2803** [protofire/solhint#311]
Hey I just wanted to point out that in the documentation of your tool you don't mention the json output format (which is the most useful one). I though it was not supported, as you just mention (stylish, table, tap, unix), but I tried passing 'json' as a format and it actually works.

Maybe it should be added to the documentation or to the repo README file ?

**Comment by dbale-altoros** [comment]
Added in docs and fixed a minor bug
https://github.com/protofire/solhint/pull/440
