### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Siegrift** [protofire/solhint#317]
Hi, solhint formatter just crashed on my one of my contracts. See the minimal example below to reproduce:

```solidity
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.9;

contract TestDecoder {
    function decodeNestedArray(bytes calldata data)
        public
        pure
        returns (int256[2][][3] memory decodedData)
    {
        decodedData = abi.decode(data, (int256[2][][3]));
    }
}
```

Solhint config:
```json
{
  "extends": "solhint:recommended",
  "rules": {
    "compiler-version": "off",
    "func-visibility": ["warn", { "ignoreConstructors": true }],
    "not-rely-on-time": "off",
    "no-empty-blocks": "off"
  }
}
```

solhint version: `"solhint": "^3.2.0"`

This is actually an parser issue, so this might not be the best place for this issue. Full trace:
![image](https://user-images.githubusercontent.com/22679154/140922042-4d490933-3e01-44ce-8ca7-2b71629761d7.png)

**Comment by Siegrift** [comment]
Also breaks with solhint version `3.3.6`

**Comment by dbale-altoros** [comment]
This issue is fixed when upgrading to the last solidity parser version (0.14.5)
https://github.com/protofire/solhint/pull/378
