### ISSUE TITLE
unkown option --init

### ISSUE THREAD

**Issue by aster2709** [protofire/solhint#319]
hi. installing solhint globally and running `--init` creates a config file
but installing it as a local dependency and running `npx solhint --init` says unknown options

![image](https://user-images.githubusercontent.com/39130640/143686952-fdba49a9-78f0-4a36-8f38-b6eafb3524f5.png)

**Comment by dbale-altoros** [comment]
@aster2709 
can you provide more info ?
OS ?

I tried this in three different repos on different computers and this error is not happening
If you still have this issue, please post in comments. 
I close this for now.
