### ISSUE TITLE
`ignoreConstructors` not working in rule: `func-visibility`

### ISSUE THREAD

**Issue by aster2709** [protofire/solhint#320]
hey setting `ignoreConstructors` to `true` still gives the warning
![image](https://user-images.githubusercontent.com/39130640/143687537-2ce90a69-f29d-4f33-99cc-ea8a97459568.png)

**Comment by dbale-altoros** [comment]
Tested but cannot seems to find any issue:
`ignoreConstructors": false`

![image](https://github.com/protofire/solhint/assets/89921440/7c8a4cef-f5f8-4955-970c-9e6ee91594c5)

Left an error on semver on purpose, just for showing solhint was executed

`ignoreConstructors": true`

![image](https://github.com/protofire/solhint/assets/89921440/f0c465c5-8809-46a6-99d7-0c84f1abc537)

Also all the test are passing ok...

**Comment by dbale-altoros** [comment]
Closed due to lack of user feedback
Check the new version release !
Feel free to comment if you have any issue
