### ISSUE TITLE
Parse error for `unchecked` blocks

### ISSUE THREAD

**Issue by lukehutch** [protofire/solhint#321]
Using the SolHint plugin for Remix, I get `Error: Parse error: missing ';' at '{'` with the following code, at the line marked `// (*)`:

```
        unchecked {   // (*)
            _balances[sender] = balance - amount;
        }
```

I assume this means SolHint does not yet support the syntax of Solidity 0.8.0+?

**Comment by dbale-altoros** [comment]
Since v0.11.0 of the parser, this issue has been resolved. [Parser Releases](https://github.com/solidity-parser/parser/releases)
![image](https://user-images.githubusercontent.com/89921440/212723478-249f2917-eb8b-4159-b2de-d1a5b8836f62.png)
