### ISSUE TITLE
check-send-result: false positives for ERC777 send() calls

### ISSUE THREAD

**Issue by d10r** [protofire/solhint#325]
The rule incorrectly triggers for invocations of [ERC777.send(address, uint256, bytes)](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC777/ERC777.sol#L130).

Looking at the code for the rule, I guess this could be prevented by additionally checking the number (and/or type) of arguments in [validateSend](https://github.com/protofire/solhint/blob/991b8755ef2babcc2c97c278b039c86abeef4b8a/lib/rules/security/check-send-result.js#L45).

**Comment by dbale-altoros** [comment]
Solved in this pr
https://github.com/protofire/solhint/pull/477

Sorry for the late response.
There is a new release available and we will be updating solhint on regular basis with a dedicated team to it
New release tomorrow!
Thanks for posting
