### ISSUE TITLE
Enforce function return values to be named

### ISSUE THREAD

**Issue by 0xGorilla** [protofire/solhint#340]
I would like to be able to enforce functions to have they return values named.

Passes:
`function something() external view returns (bool _isValid) {}`

Warns:
`function something() external view returns (bool) {}`

I can create a custom rule if necessary, but, is there any way to identify a node as being a return value? Didn't manage to find one

**Comment by dbale-altoros** [comment]
@0xGorilla 
For this function
`function getValueNamed() public returns (uint vuelta) {
    vuelta = value;    
  }`

The AST will be like this:
![image](https://github.com/protofire/solhint/assets/89921440/03b6154a-d615-424d-add4-70da3f65585a)

Inside the FunctionDefinition node you can find the returnParament node with the inherent data

This rule could be a good addition!

**Comment by dbale-altoros** [comment]
@0xGorilla 
Added rule in:
https://github.com/protofire/solhint/pull/478

Sorry for the late response.
There is a new release available and we will be updating solhint on regular basis with a dedicated team to it
New release tomorrow Friday
Thanks for posting
