### ISSUE TITLE
Suggestion - shadows

### ISSUE THREAD

**Issue by muturgan** [protofire/solhint#345]
It could be great to show that a function parameter declaration shadows an existing state declaration

**Comment by dbale-altoros** [comment]
@muturgan 
Seems like this check is already implemented in the compiler itself
Why do you need it in solhint ?

**Comment by dbale-altoros** [comment]
Closed due to lack of user feedback
Check the new version release !
Feel free to comment if you have any issue

![image](https://github.com/protofire/solhint/assets/89921440/39120359-b3f0-4aa6-ba4c-3d4b6180d72e)
