### ISSUE TITLE
SolHint - Updating grammar for accepting underscores in Integers

### ISSUE THREAD

**Issue by PedroReyes** [protofire/solhint#348]
Hello,

❌ Error
For the next code:

```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.10;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract BUSD is ERC20 {
    uint256 public INITIAL_SUPPLY = 100_000_000e18;

    constructor() ERC20("BUSD", "BUSD") {
        _mint(msg.sender, INITIAL_SUPPLY);
    }
}
```

when running `npx hardhat check` I get the next result:

```
$ npx hardhat check
line 7:39 extraneous input '_000_000e18' expecting ';'
``` 

ℹ Expected
This way of typing numbers (`100_000_000e18`) in solidity is quite useful and accepted. What about updating SolHint in this regard for not identifying this symbol as `extraneous input`?

Source: [Rational and Integer Literals](https://docs.soliditylang.org/en/latest/types.html?highlight=number%20literals#rational-and-integer-literals)

Best regards,
Pedro Reyes.

**Comment by dbale-altoros** [comment]
@PedroReyes 
I would recommend to execute solhint without the hardhat embedded task
And please get the latest version
I'm testing contracts typing numbers like that and I'm not getting any error

**Comment by dbale-altoros** [comment]
Closed due to lack of user feedback
New version is released
Feel free to comment if you have any issue
