### ISSUE TITLE
Add a rule for recommending custom errors instead of revert reason strings

### ISSUE THREAD

**Issue by PaulRBerg** [protofire/solhint#349]
I'm thinking of something similar to [no-inline-assembly](https://github.com/protofire/solhint/blob/3443eee94de7dbda7ad3abd5d3540c3a96e95a0f/docs/rules/security/no-inline-assembly.md), but for custom errors versus revert reason strings. Maybe "no-revert-reason-strings"?

[Custom errors](https://blog.soliditylang.org/2021/04/21/custom-errors/) are more elegant and much more gas efficient than revert reason strings, but in spite of that revert reason strings are still more popular (at least based on my experience).

**Comment by dbale-altoros** [comment]
Done in
https://github.com/protofire/solhint/pull/475
