### ISSUE TITLE
Do we need to update the read me file?

### ISSUE THREAD

**Issue by alakhkaushik** [protofire/solhint#357]
![image](https://user-images.githubusercontent.com/20486289/196851447-c148dc3c-4d45-4ca9-9e21-1ee4fbb4fe6a.png)

When I try --init command to configure the generated .solhint.json file has different default config like below but not what readme file mentions... I wondered is there anything wrong with my installation / dependencies or it's just outdated readme file?

`
{
  "extends": "solhint:default"
}
`

**Comment by dbale-altoros** [comment]
done in last version (3.4.1)
