### ISSUE TITLE
How to Import org-scoped plugins from NPM? @org/solhint-plugin-foo

### ISSUE THREAD

**Issue by yosriady** [protofire/solhint#358]
According to the docs, custom plugins need to follow the `solhint-plugin-*` naming convention.

I'm trying to publish a Solhint plugin under our `@org/package-name` in NPM and Solhint is unable to detect the plugin because the prefix has the org name.

How do I import org-scoped plugins to Solhint?

**Comment by yosriady** [comment]
The package is https://www.npmjs.com/package/@chainlink/solhint-plugin-chainlink-solidity

**Comment by yosriady** [comment]
The following works:

```
    "solhint-plugin-chainlink-solidity": "npm:@chainlink/solhint-plugin-chainlink-solidity@^1.0.0"
```

**Comment by coreyar** [comment]
In the documentation they show
```json
{
  "extends": "solhint:recommended",
  "plugins": ["chainlink-solidity"]
 }
```
