### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#373]
The dependencies used by Solhint haven't been updated in a while.

Running `npm outdated`, updating the ones that need it, and verifying that nothing breaks should be enough.

**Comment by frangio** [comment]
ESLint is particularly outdated and contributes a lot to installation size.

**Comment by juanpcapurro** [comment]
gave it a try on #380 :sparkles:

**Comment by dbale-altoros** [comment]
merged
