### ISSUE TITLE
test the different formatters

### ISSUE THREAD

**Issue by juanpcapurro** [protofire/solhint#386]
in the process of implementing #385 I removed one of the formatters and didn't get any test failure

the goal of this issue is to discuss:

- adding cases to the integration tests to at least run every formatter once
- backporting unit tests for the formatter themselves from eslint's repository

**Comment by dbale-altoros** [comment]
This PR https://github.com/protofire/solhint/pull/457
Adds the 'compact' formatter option
Adds some summary info in compact, unix and json formatters
Adds e2e test to each formatter
