### ISSUE TITLE
Add `explicit-types` rule

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#387]
### Summary
Add a new `explicit-types` rule to forbid or enforce explicit types (like `uint256`) that have an alias (like `uint`). This rule should implement the auto-fix mechanism.

### Motivation
Prettier Solidity used to have an option to do this, but it was removed in v1.0.0 because we felt that that kind of thing belongs to a linter rather than a formatter.

### Details
The rule should accept an options object `{ default: "explicit" | "implicit" }`, where "explicit" means that `uint256`, `int256`, etc. should be used and "implicit" means that `uint`, `int`, etc. should be used. The default should be "explicit".

The types that should be affected are:
- `uint256` and `uint`
- `int256` and `int`
- `ufixed128x18` and `ufixed`
- `fixed128x18` and `fixed`

I'm intentionally not including `bytes1` and `byte`. The reason is that, since we don't have version information, we can't know if an instance of `bytes1` (with the implicit default selected) is an error or not. If there's demand for this, we might consider adding a new option to the rule.

**Comment by dbale-altoros** [comment]
@fvictorio 
I understand the rule...
One thing I'm missing
As I see in the code...
The rules are configured like this:
```
{
  "rules": {
    "max-line-length": ["error",120]
  }
}
```
So when you say it should accept an object { default: "explicit" | "implicit" }

```
{
  "rules": {
    "explicit-types": ["error","explicit"]
  }
}
```
Or you meant another thing ?

**Comment by fvictorio** [comment]
```
{
  "rules": {
    "explicit-types": ["error", { default: "implicit" }]
  }
}
```

**Comment by shirotech** [comment]
In the meantime, I have been maintaining a direct fork with that feature backported, if anyone is interested https://www.npmjs.com/package/prettier-plugin-solidity-explicit-types

**Comment by dbale-altoros** [comment]
Added in this PR
https://github.com/protofire/solhint/pull/467
