### ISSUE TITLE
`initializer` modifier should be treated as constructor within `ordering` rule

### ISSUE THREAD

**Issue by shirotech** [protofire/solhint#404]
In an upgradable proxy, there is no concept of "constructor", rather they have an `initialize` function with an `initializer` modifier. For example:

https://github.com/protofire/solhint/blob/master/lib/rules/order/ordering.js#L142

```sol
function initialize() public initializer {
  // initialize member properties here
}
```

**Comment by dbale-altoros** [comment]
This is fixed in this pr
https://github.com/protofire/solhint/pull/474
