### ISSUE TITLE
Remove Travis and add a GH workflow file to run the lint and test scripts

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#409]
Tests are failing in `master`. I think the reason this wasn't noticed is that Travis stopped working for some reason. The easiest fix is to just remove the `.travis.yml` file (and the badge in the readme) and to add a GitHub workflow that runs the linter and the tests.

**Comment by dbale-altoros** [comment]
I did this PR
https://github.com/protofire/solhint/pull/412
Linter is already being executed in the E2E.yml so I just added the tests to this one
It is failing now because of the not-rely-on-time rule
I'll wait until we revert that pr and then will try the #412 pr to check everything is working
