### ISSUE TITLE
Add easily accessible list of depreciated rules

### ISSUE THREAD

**Issue by chriscrutt** [protofire/solhint#426]
For example, I have every rule enabled in VSCode just to see what I can make more uniform, etc. After trying to figure out how to [mark an external contract as trusted](https://github.com/protofire/solhint/blob/master/docs/rules/security/mark-callable-contracts.md), I found that that rule was depreciated.

I haven't had time to look through each rule and see what is depreciated and what isn't but it'd be nice if there was an easy way to filter through or see what is depreciated.

**Comment by dbale-altoros** [comment]
Good point
I added a deprecated mark on this readme
https://github.com/protofire/solhint/blob/master/docs/rules.md
In this PR
https://github.com/protofire/solhint/pull/444

**Comment by dbale-altoros** [comment]
![image](https://github.com/protofire/solhint/assets/89921440/a9a51230-8697-4a1a-a956-f7c3741eba38)
