### ISSUE TITLE
create enable-all extention

### ISSUE THREAD

**Issue by chriscrutt** [protofire/solhint#427]
solhint has some great rules that aren't enabled with the default or recommended extensions. For someone that wants to go super overkill, it'd be nice to have an extension that could enable all rules (except for depreciated ones?).

**Comment by fiction-code** [comment]
You can use `"extends": "solhint:all"` to include all rules, excluding deprecated ones. Also, `default` and `recommended` extensions don't include rules that are marked as deprecated too.
