### ISSUE TITLE
Disable rules using "off" instead of "false"

### ISSUE THREAD

**Issue by fvictorio** [protofire/solhint#43]
In order to make solhint more compatible with eslint, we should allow disabling rules using the value `"off"` instead of using `false`. We can make this change backward-compatible and, ideally, show a deprecated message for configurations that use `false`.

**Comment by idrabenia** [comment]
Hi, It's break backward compatibitilies. 

I think it make sense to concentrate on business features instead of this small improvements

**Comment by fvictorio** [comment]
I meant we could have both options, so that it's backwards compatible. I think a lot of users coming from eslint are used to using `"off"` instead of `false` (I myself tried to do it).

I agree that this is low priority, but it's the kind of thing that someone looking to collaborate could use as a first issue.

**Comment by pablofullana** [comment]
Now that we have 2.0 about to be released, and for the good of simplicity, why don't we simply get rid of "`false` and stick to `0 | 'off'`? (keeping in mind that we wanna mimic eslint behavior when possible).

**Comment by fvictorio** [comment]
For the record: `0` and `'off'` are still valid. Since we already published 2.0, the only thing we can do is deprecate them.
