### ISSUE TITLE
The `--fix` option not working

### ISSUE THREAD

**Issue by rndquu** [protofire/solhint#434]
Hi guys, running `solhint AccessControlFacet.sol --fix` does not fix solhint errors.

Versions:
```
yarn: 3.2.3
solhint: 3.4.1
```

Solhint config:
```
{
  "rules": {
    "quotes": ["error","double"]
  }
}
```

AccessControlFacet.sol:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {IAccessControl} from '../interfaces/IAccessControl.sol';

...other code
```

Running `solhint AccessControlFacet.sol` gives an expected error:
```
4:30  error  Use double quotes for string literals  quotes

✖ 1 problem (1 error, 0 warnings)
```

Now when the `--fix` options is added and I run this command `solhint AccessControlFacet.sol --fix` then single quotes are not updated to double quotes. I expected that solhint will replace single quotes to double quotes. What am I doing wrong?

**Comment by dbale-altoros** [comment]
Hello, for now, the `--fix` option currently works only on "avoid-throw" and "avoid-sha3" rules
As a matter of fact I just corrected a bug on the avoid-throw rule in this PR
https://github.com/protofire/solhint/pull/442
