### ISSUE TITLE
restore 'compact' formatter

### ISSUE THREAD

**Issue by juanpcapurro** [protofire/solhint#435]
It was removed recently when updating dependencies, and at least [ALE](https://github.com/dense-analysis/ale) requires it.

**Comment by dbale-altoros** [comment]
@juanpcapurro what do you mean by compact formatter

now we have:
- table
- unix
- tap
- stylish
- json (new one)

**Comment by dbale-altoros** [comment]
This PR https://github.com/protofire/solhint/pull/457
Adds the 'compact' formatter option
Adds some summary info in compact, unix and json formatters
Adds e2e test to each formatter
