### ISSUE TITLE
Setup solhint to fail github CI on any warning with `--max-warnings 0`

### ISSUE THREAD

**Issue by vladikopl01** [protofire/solhint#460]
I set up solhint for GitHub CI workflow as a linter for solidity files: `solhint --max-warnings 0 \"contracts/**/*.sol\"`. But CI is not failing on warnings provided by solhint.

How could it be implemented?
Thanks

**Comment by dbale-altoros** [comment]
@vladikopl01 
There was an issue with max warnings which is fixed here:
https://github.com/protofire/solhint/pull/439/files

FYI: 
When setting max-warnings, if solhint finds more than the number configured, it should exit with code 1 and a message:
`Solhint found more warnings than the maximum specified`
This will be the behavior

**Comment by dbale-altoros** [comment]
@vladikopl01 New version is released
Please try it and let me know if you have any issue

**Comment by 0xCourtney** [comment]
> @vladikopl01 New version is released Please try it and let me know if you have any issue

Just tested this out and it works fine for us.

**Comment by dbale-altoros** [comment]
@0xCourtney thanks a lot for that!
