### ISSUE TITLE
[Feature Request] Watch mode

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/solhint#47]
Hello, It would be nice to have the option "--watch" or a kind of watch mode, where you can see errors and problems in real time. 

Thanks in advance

**Comment by pablofullana** [comment]
At the moment, there are no plans for watch mode support to be shipped with Solhint. Instead, [Solhint Watch](https://www.npmjs.com/package/solhint-watch) should do the trick.

**Comment by pablofullana** [comment]
I'll close this issue for now, and we could re-open it in case we decide to support watch mode from Solhint itself.
