### ISSUE TITLE
Can't install solhint through yarn/npm package manager

### ISSUE THREAD

**Issue by Skythrill256** [protofire/solhint#495]
![Screenshot from 2023-09-04 17-09-27](https://github.com/protofire/solhint/assets/113181374/d991ea6d-7a4b-4ee9-82f4-c8bd4099944c)
 
This error is showing

**Comment by dbale-altoros** [comment]
@Skythrill256 
I'm not a mac user
But in Linux I would try to install this by using 
sudo
So installation is done by root user

Can you try that ?

**Comment by dbale-altoros** [comment]
Closed due to lack of user feedback
Check the new version release !
Feel free to comment if you have any issue
