### ISSUE TITLE
"no-empty-blocks": ["error", { "ignoreConstructors": true }] not working

### ISSUE THREAD

**Issue by CJ42** [protofire/solhint#496]
I have the following `.solhint.json` config file:

```json
{
  "extends": "solhint:recommended",
  "rules": {
    "avoid-sha3": "error",
    "avoid-suicide": "error",
    "avoid-throw": "error",
    "avoid-tx-origin": "error",
    "check-send-result": "error",
    "compiler-version": ["error", "^0.8.0"],
    "func-visibility": ["error", { "ignoreConstructors": true }],
    "not-rely-on-block-hash": "error",
    "not-rely-on-time": "error",
    "reentrancy": "error",
    "constructor-syntax": "error",
    "private-vars-leading-underscore": ["error", { "strict": false }],
    "imports-on-top": "error",
    "visibility-modifier-order": "error",
    "no-unused-import": "error",
    "no-global-import": "error",
    "reason-string": ["warn", { "maxLength": 120 }],
    "avoid-low-level-calls": "off",
    "no-empty-blocks": ["error", { "ignoreConstructors": true }],
    "custom-errors": "off"
  }
}
```

The option `ignoreConstructors` is set to `true`, but does not work with the following contract:

```solidity
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.4;

/**
 * @dev sample contract used for testing
 */
contract PayableContract {
    constructor() payable {}

    // solhint-disable no-empty-blocks
    function payableTrue() public payable {}

    // solhint-disable no-empty-blocks
    function payableFalse() public {}
}
```

After running 

```
➜  lsp-smart-contracts git:(DEV-8062) ✗ npx solhint 'contracts/Mocks/PayableContract.sol'

contracts/Mocks/PayableContract.sol
  8:27  error  Code contains empty blocks  no-empty-blocks

✖ 1 problem (1 error, 0 warnings)
```

**Comment by dbale-altoros** [comment]
@CJ42 
sorry but there is no such configuration for that rule

see https://github.com/protofire/solhint/blob/master/docs/rules/best-practises/no-empty-blocks.md

you can open an issue to suggest adding that... we can address it for forthcoming versions

**Comment by CJ42** [comment]
This release suggests that this option exist

https://github.com/protofire/solhint/releases/tag/3.5.1

![image](https://github.com/protofire/solhint/assets/31145285/479c1111-1f60-4578-a132-80746e479190)

**Comment by dbale-altoros** [comment]
omg!
That is weird
I'll check that asap
@CJ42 sorry for the bad response

**Comment by dbale-altoros** [comment]
ok... I checked
See this thread for more info:
https://github.com/protofire/solhint/pull/418

The changelog is missleading there is no such option... you can check the code. There is no configuration option for that rule as stated in the rule help readme
https://github.com/protofire/solhint/blob/develop/lib/rules/best-practises/no-empty-blocks.js

The rule just ignores an empty constructor as long as a base contract is being inherited
It will ignore this:

```
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.4;

import { ERC20Burnable} from "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";

contract PayableContract is ERC20Burnable{
    constructor() ERC20("MyToken", "MTK") {}

    // solhint-disable no-empty-blocks
    function payableTrue() public payable {}

    // solhint-disable no-empty-blocks
    function payableFalse() public {}
}
```

But it will be a warning to this:
```
// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.4;

contract PayableContract {
    constructor() {}

    // solhint-disable no-empty-blocks
    function payableTrue() public payable {}

    // solhint-disable no-empty-blocks
    function payableFalse() public {}
}
```

Because there is no need to define an empty constructor...

**Comment by CJ42** [comment]
@dbale-altoros Ok that makes sense, thank you for the clarification!
It would be good to document this imo (either in the Release detail or somewhere else), as it is not immediately clear when reading the CHANGELOG.

**Comment by dbale-altoros** [comment]
yes will do
