### ISSUE TITLE
Access all existing rules of solhint in a programatic way

### ISSUE THREAD

**Issue by carlospinho04** [protofire/solhint#51]
Is there any way to access all existing rules of solhint in a programatic way?

For instance the method through which the documentation files are created, if they are made automatically?

**Comment by fvictorio** [comment]
Hi @carlospinho04, could you give us an example of how you would use something like this?

**Comment by carlospinho04** [comment]
I'm trying to generate a json with the rules, descriptions, parameters, etc.

Something like `solhint --list-rules` would be great.

**Comment by fvictorio** [comment]
Do you think something similar to [`eslint --print-config file`](https://eslint.org/docs/user-guide/command-line-interface#--print-config) would work for you? Notice that you have to indicate a file, because the rules can change for different paths.

**Comment by carlospinho04** [comment]
What i really need is a command that gives me all the rules available in this linter.

**Comment by fvictorio** [comment]
Well, doing that would give you a `rules` object and you could use the keys of that object to have the list of rules.

**Comment by dbale-altoros** [comment]
This is available in this PR
https://github.com/protofire/solhint/pull/449

To see all rules just change the .solhint.json to:

`{
  "extends": "solhint:all",
  "rules": {}
}`
