### ISSUE TITLE
Add an official docker image for solhint

### ISSUE THREAD

**Issue by kaypee90** [protofire/solhint#521]
Currently, there are a number of Solhint images on [DockerHub](https://hub.docker.com/search?q=Solhint) which are not being maintained.

Can we have an official docker image that will be maintained and kept up to date?

**Comment by kaypee90** [comment]
@dbale-altoros I have opened a PR for this.

**Comment by dbale-altoros** [comment]
https://github.com/protofire/solhint/pull/524
