### ISSUE TITLE
private-vars-leading-underscore on internal functions in libraries is not a best practice

### ISSUE THREAD

**Issue by ZumZoom** [protofire/solhint#523]
In #511 a change was made to treat library internal functions the same way they are treated in contracts. Almost all of the solidity libraries are not using underscore for internal functions naming. Even in the official docs they don't use underscores on internal functions in libraries https://docs.soliditylang.org/en/latest/contracts.html#libraries.

**Comment by dbale-altoros** [comment]
@ZumZoom good catch
we will review this
thanks for the input!

**Comment by dbale-altoros** [comment]
Corrected here
https://github.com/protofire/solhint/pull/525
