### ISSUE TITLE
no-simple-event-func-name should have an exception of ERC20 token

### ISSUE THREAD

**Issue by tjayrush** [protofire/solhint#53]
ERC 20 is a standard. Unfortunately, they named their `Transfer` event the same as their `transfer` function.

You're correct in marking this as a warning if `no-simple-event-func-name` is being checked, but I think it's a bad idea to do so. 

A nieve programmer may change that event name to something else, only to silence the linter, but this will make the token contract non-compliant. In order to remove the warning, the programmer must create an incompatible client.

I would make an exception and not report a warning if the smart contract is an ERC20 token (which may be impossible, but in that case simply don't warn for the Transfer(address indexed, address indexed, uint256) event.

**Comment by fvictorio** [comment]
I see two options here:

1. Not having that rule enabled by default.
2. Allowing the user to set exceptions. In this case it would be something like: `"no-simple-event-func-name": ["on", { exclude: ["Transfer"] }]`

**Comment by fvictorio** [comment]
> The linter throws a warning on the constant variables `name`, `symbol`, and `decimals` not being in all CAPS.

I think this rule is too opinionated. We are in the process of taking this kind of rules out of the default, making them opt-in (maybe through a plugin) and leaving only the more security-focused rules.

**Comment by mswezey23** [comment]
I don't mind enforcing good coding practices, but when we have standards that do not follow said practices... that leads to many frustrations down the road. 

I'd like to opt-in for it, but also have the linter be "intelligent" enough to detect that the current code is part of an ERCXXX standard. That was approved with bad practices being enforced, and ignore whatever bad practices the ERC at hand is implementing. Without having to disable/enable rules via comments surrounding blocks of code. 

Maybe I'm too picky 😂

**Comment by pablofullana** [comment]
hey @mswezey23 thanks for the feedback. I really like the idea of checking if a given code is PERCXYZ compliant, looks to me that it's worth researching into it. First thing that comes to my mind is checking that it matches proposed interface. Do you think there may be other stuff to check/validate?

**Comment by mswezey23** [comment]
Hey @pablofullana, thanks for the reply. 
Checking the interface is a great first step which would be defined as the ABI. 
Which, if I'm not mistaken, would cover these lowercased variable names since the compiler auto generates the `getter` functions. 

They're maybe other things to check or validate that pop up as this adventure unfolds. 
I wouldn't mind helping this effort by dedicating a couple hours or so every week. Let me know :)

**Comment by fvictorio** [comment]
Thanks @mswezey23, contributions are totally welcome!

You can take https://github.com/protofire/solhint/issues/43 if you are interested. It's been open for a while now, and I think it's a good place to start contributing.

**Comment by nventuro** [comment]
I ended up disabling this rule globally: I find that forcing events to use CamelCase and functions to use mixedCase is enough to differentiate them.

**Comment by dbale-altoros** [comment]
This rule is no longer available
