### ISSUE TITLE
[Feature request] Add max-warnings option

### ISSUE THREAD

**Issue by florblue** [protofire/solhint#56]
Add --max-warnings [int] option in formatter option: Number of warnings to trigger nonzero exit code.

Number of warnings to trigger nonzero exit code - default: -1

The motivation comes from an option that EsLint CLI offers, and continue tha idea of issue #5.

**Comment by pablofullana** [comment]
@fvictorio shall we close this one?

**Comment by fvictorio** [comment]
Yep.
