### ISSUE TITLE
Use solidity-parser-antlr?

### ISSUE THREAD

**Issue by sohkai** [protofire/solhint#6]
Not sure if there was a licensing issue ([solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr) is GPL, which would force this project to be GPL?) or something, but a quick look over a diff of the antlr grammars in this package and `solidity-parser-antlr` make it seem like the differences are trivial, and hence unnecessary to maintain two copies.

The only non-trivial differences seem to be a few extra rules here for some assembly items, namely [`subAssembly`, `datasize`, and `linkerSymbol`](https://github.com/protofire/solhint/blob/master/lib/grammar/Solidity.g4#L271) and [one potentially wrong rule for `expression`](https://github.com/protofire/solhint/blob/master/lib/grammar/Solidity.g4#L212) (AFAIK you can only use an identifier after a `.`).

**Comment by idrabenia** [comment]
Hi @sohkai ,

Take control over grammar has some advantages. We can create additional nodes and Solhint do not breaks after new release of library.

Then I think it make sense to store Solhint grammar there.

Thanks!
\- Ilya

**Comment by sohkai** [comment]
Sorry for the late response @idrabenia.

Just wanted to clarify a few things that might sway you over, but I understand if you / Protofire want to keep control over the parsing.

> We can create additional nodes

Are there specific, specialized nodes that Solhint might use (e.g. for internal parsing / clarification) that would not be useful for the general community? If not, then any new nodes would probably be an improvement over the current parsers anyway, and it'd be nice to be able to merge that upstream so everyone can benefit :).

> Solhint do not breaks after new release of some dependent library.

You could pin the version number you depend on, and upgrade as necessary.

--------------

My goal in having everyone use the same parser is to avoid fragmentation and centralize the errors of any parsing functionality.

For example: https://github.com/protofire/solhint/issues/9; this seems to be a issue in the original parser that would be nice to fix upstream rather than in every clone.

**Comment by federicobond** [comment]
Hi there! I'm the maintainer of [solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr/). Just wanted to say I really like `solhint` and I think it's a great addition to the community, but I'm pretty sure that you copied and reformatted my original grammar located at [solidityj/solidity-antlr4](https://github.com/solidityj/solidity-antlr4/blob/master/Solidity.g4), which constitutes a violation of the original license (the [history](https://github.com/protofire/solhint/commits/master/lib/grammar/Solidity.g4) of the file in your repo makes it very clear).

I understand your need to move fast and have control of the grammar, but a quick heads-up would have likely cleared up any issues and open up a way for both projects to collaborate.

I have no interest in pursuing legal action, as I do this out of love for the ecosystem, but I would appreciate if you reconsidered your stance. Thank you and happy holidays! 🎄
