### ISSUE TITLE
Multi-line stubs/events violate "separate-by-one-line-in-contract"

### ISSUE THREAD

**Issue by ajhodges** [protofire/solhint#74]
I've been really happy with solhint so far, thanks for the great tool. I have one thing that I just ran into that doesn't make sense to me, even though I think _technically_ it adheres to the official solidity style guide:

```
contract MyContract is Ownable {
    event EscrowDeposited(address indexed msgSender, bytes16 indexed myCoolUuid, uint256 amount);
    event EscrowFunded(address indexed msgSender, bytes16 indexed myCoolUuid, uint256 funded, uint256 contracted);
    event EscrowReleased(address indexed msgSender, bytes16 indexed myCoolUuid, uint256 amount);
    event EscrowRefunded(address indexed msgSender, bytes16 indexed myCoolUuid, uint256 amount);
    event EscrowWithdrawn(address indexed msgSender, bytes16 indexed myCoolUuid, uint256 amount);

    event EscrowCreated(address indexed msgSender, bytes16 indexed myCoolUuid, Escrow.FundingType fundingType,
                        uint256 contractedAmount);
}
```

I had to make one of my event declarations span multiple lines, since it was longer than 120 chars. Since my event now spans two lines, the `separate-by-one-line-in-contract` rule now applies to it.

Visually, I think it's nicer to have all my related events grouped together, and I don't think this case really fits the spirit of what was intended when this rule was defined in the [Solidity style guide](https://solidity.readthedocs.io/en/v0.4.24/style-guide.html#blank-lines): `Blank lines may be omitted between groups of related one-liners (such as stub functions for an abstract contract)`.

**Comment by fvictorio** [comment]
Hi @ajhodges, thanks for opening this.

I'm not sure what is your suggestion here. You can just disable that rule, can't you? Or are there scenarios where this rule makes sense and you want it on, but not others? If that's the case, could you give us some examples of what you think would be "right" and "wrong" scenarios for this rule?

By the way, we are planning on making all rules opt-in in the next major version, so you can just enable the ones that make sense for you. And we are working on integrating with the solidity plugin for prettier (I just updated the readme, in case you are interested) to delegate all styling decisions to that plugin. Prettier respects your empty lines, so at least this problem shouldn't show up.

**Comment by ajhodges** [comment]
I'm not sure if I have a recommendation - I just wanted to have an open discussion. The `separate-by-one-line-in-contract` rule makes a lot of sense, and I like having it enabled. However the rule seems to be aimed at separating functions, modifiers, structs, etc with whitespace. There is an exclusion for stub functions and events - I guess my recommendation is to add an exclusion for multi-line stubs/events. It feels really inconsistent to have to add a blank line in-between events and stub functions if they have to span multiple lines.

Here are some examples using the ERC20Basic interface from OpenZeppelin
Original:
```
contract ERC20Basic {
  function totalSupply() public view returns (uint256);
  function balanceOf(address _who) public view returns (uint256);
  function transfer(address _to, uint256 _value) public returns (bool);
  event Transfer(address indexed from, address indexed to, uint256 value);
}
```

Expected (IMO? I guess?):
```
contract ERC20Basic {
    function totalSupply() public view returns (uint256);
    function balanceOf(address _who) public view returns (uint256);
    function exampleOfAReallyLongAbstractFunction(address arg1, address arg2, address arg3, address arg4)
        public view returns (address);
    function transfer(address _to, uint256 _value) public returns (bool);
    event LogTransferLong(address indexed from, address indexed to, uint256 value, address arg4, address arg5,
                          address arg6);
    event LogTransfer(address indexed from, address indexed to, uint256 value);
}
```

Correct according to Solhint:
```
contract ERC20Basic {
    function totalSupply() public view returns (uint256);
    function balanceOf(address _who) public view returns (uint256);

    function exampleOfAReallyLongAbstractFunction(address arg1, address arg2, address arg3, address arg4)
        public view returns (address);

    function transfer(address _to, uint256 _value) public returns (bool);

    event LogTransferLong(address indexed from, address indexed to, uint256 value, address arg4, address arg5,
                          address arg6);

    event LogTransfer(address indexed from, address indexed to, uint256 value);
}
```

**Comment by fvictorio** [comment]
> I'm not sure if I have a recommendation - I just wanted to have an open discussion.

Yes, sorry, I didn't mean to imply that you *had* to have one. Triggers for discussions like this are welcome :slightly_smiling_face: 

> It feels really inconsistent to have to add a blank line in-between events and stub functions if they have to span multiple lines.

I agree with this. Only the kind of element (event, stub function) should matter, not how many lines spans.

**Comment by fvictorio** [comment]
Closing this since we removed all styiling rules. Check 3.0 release notes for more information.
