### ISSUE TITLE
Support for Solidity 0.5.x

### ISSUE THREAD

**Issue by nventuro** [protofire/solhint#84]
Hi everyone, thanks for the great work on this!

I'm considering migrating from Solium (now Ethlint) to Solhint for OpenZeppelin (there was a request back in the day for this: https://github.com/OpenZeppelin/openzeppelin-solidity/issues/508). The whole thing seems pretty solid, but I found the latest release (v1.4 - by the way, `solhint --version` outputs 1.1.10, you probably [want to fix that](https://github.com/protofire/solhint/blob/v1.4.0/solhint.js#L10) :) ) doesn't support 0.5.x code. 

I noticed there's a recent PR for this (https://github.com/protofire/solhint/pull/79), but there doesn't seem to be a release including it. Do you have a time estimate for a release where this may be added? 

Thanks!

**Comment by mariano-aguero** [comment]
Hi @nventuro 
Thanks for your feedback, is always welcome! We released a new version including the new grammar, also we fix the problem you [notified](https://github.com/protofire/solhint/blob/v1.4.1/solhint.js#L12)
Feel free to reopen the issue if the problem was not resolved.

Best regards
