### ISSUE TITLE
Data location "calldata" in external function parameters throws an "Unused variable" error

### ISSUE THREAD

**Issue by clemlak** [protofire/solhint#96]
This error occurs when using Truffle 5 and Solidity 0.5.0.
Solidity 0.5.0 requires to specify the location of the data of external function parameters, but when using `calldata`, Solhint thinks it's the name of a variable and throws an unused variable error.

Here is a small example:  
`function foo(bytes calldata bar) external returns (bool)`

**Comment by mariano-aguero** [comment]
Hello @clemlak , I was not able to reproduce the issue.

These are the steps to reproduce the problem
- Installed solc 0.5.0 (Version: 0.5.0+commit.1d4f565a.Linux.g++)
- Installed Truflle 5.0.0 (Version: Truffle v5.0.0)
- I created a smart contract with an interface as you describe it ( `function foo(bytes calldata bar) external returns (bool);` ) 
- I used the following solhint configuration:
```
{
  "extends": ["solhint:recommended"]
}
```

Let us know if you are still facing this issue and have more details, so we can take a deeper look at it. Thanks!
