### ISSUE TITLE
Fix mode

### ISSUE THREAD

**Issue by pablofullana** [protofire/solhint#97]
Consider adding `--fix` so offenses are auto-fixed when possible.

Open for discussion.

**Comment by fvictorio** [comment]
Not all rules will be, nor should be, fixable. So I think we can do this in two phases: first, adding _optional_ support that allows each rule to implement a "fixer". I guess this would be a function that transforms a node, but I'm not so sure about it. After that, the second phase would be to implement this for some rules, and gradually add it in all places where it makes sense.

**Comment by miguelmota** [comment]
Would be great if solhint can autofix simple things such as indentation

**Comment by fvictorio** [comment]
Hi @miguelmota. We are trying to delegate styling concerns to [`prettier-plugin-solidity`](https://github.com/prettier-solidity/prettier-plugin-solidity). It's still not 100% ready for production, but it's close enough. Maybe you can give it a try?
